# Form implementation generated from reading ui file 'info_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_info_dialog(object):
    def setupUi(self, info_dialog):
        info_dialog.setObjectName("info_dialog")
        info_dialog.resize(600, 200)
        info_dialog.setMinimumSize(QtCore.QSize(300, 200))
        info_dialog.setMaximumSize(QtCore.QSize(600, 300))
        font = QtGui.QFont()
        font.setFamily("Courier")
        info_dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(info_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=info_dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 280, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.info_label.setFont(font)
        self.info_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.info_label.setWordWrap(True)
        self.info_label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_2.addWidget(self.info_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=info_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(info_dialog)
        self.buttonBox.accepted.connect(info_dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(info_dialog)

    def retranslateUi(self, info_dialog):
        _translate = QtCore.QCoreApplication.translate
        info_dialog.setWindowTitle(_translate("info_dialog", "Error/info"))
        self.info_label.setText(_translate("info_dialog", "Placeholder text"))
